2022 extend owl2 tests
spechub/Hets pull request #2025
Opened 2021-10-26 17:23 UTC by b-gehrke

Fixes #2022

2021-11-08 14:00 UTC, b-gehrke commented
All tests pass. All warnings fixed.

2021-11-10 11:50 UTC, mcodescu requested changes
Very minor change.

2021-11-10 11:50 UTC, mcodescu commented on OWL2/StaticAnalysis.hs
> +checkHasKey :: Sign -> [AS.ObjectPropertyExpression] -> [AS.DataPropertyExpression] -> Result ([AS.ObjectPropertyExpression], [AS.DataPropertyExpression])
Shorten this line.

2021-11-11 07:34 UTC, mcodescu approved these changes
Looks good to me.
:+1:

2021-11-15 15:51 UTC, merged