1955 hermit proover integration
spechub/Hets pull request #2026
Opened 2021-10-30 09:15 UTC by erithacus-rubecula

requested pull for hermit integration branch.

2021-10-30 10:05 UTC, tillmo commented
@mcodescu can you please review this one?

2021-10-30 13:15 UTC, mcodescu commented
Yes.

2021-10-30 19:54 UTC, mcodescu commented
The last problem reported by me in the ticket #1955 is not fully solved: I see that you have added the case to `analyseOutput` but the other change was not made and therefore I get the same error when trying to disprove something. I will mark the change I had to make directly in the code. 

You should also remove the tracing messages.

2021-10-30 19:55 UTC, mcodescu requested changes

2021-10-30 19:55 UTC, mcodescu commented on OWL2/ProveHermit.hs
> +      return $ fmap (\ (_, outS, errS) -> if outS == "true\n" then (True, outS, errS) else (False, outS, errS)) mex
Using False here make the tool report it cannot find the prover. It worked for me as expected with:
`return $ fmap (\ (_, outS, errS) -> (True, outS, errS)) mex`

2021-11-03 13:51 UTC, mcodescu approved these changes
:+1:

2021-11-03 13:52 UTC, merged