2048 extend ms to whole dl
spechub/Hets pull request #2049
Opened 2022-03-23 21:35 UTC by b-gehrke

Closes #2048

2022-03-30 11:06 UTC, tillmo requested changes
looks good. Could you please add the test ontology from your thesis covering all 19 features?

2022-04-03 06:14 UTC, mcodescu reviewed
The code is fine, but Till is right: if you have more tests, please make them available.

2022-04-07 07:01 UTC, mcodescu approved these changes
:+1:

2022-04-07 07:42 UTC, tillmo approved these changes

2022-04-07 07:42 UTC, merged