2095 undefined classes for nesy patterns
spechub/Hets pull request #2096
Opened 2022-09-10 06:48 UTC by b-gehrke

Closes #2095.

Added expansion for symbols.

2022-09-15 07:20 UTC, tillmo commented
`SYMB` should be based on `node`, `Symbol` be based on `ResolvedNode`.
A `SYMB_MAP_ITEMS` can use just ontology terms, if they lead to unique id. Otherwise, the id has to specified as well. This means that the static analysis of `SYMB_MAP_ITEMS` etc. should get a signature.

2022-09-21 16:10 UTC, b-gehrke commented
@tillmo Changes are implemented as discussed. Ready for review.

2022-09-22 08:00 UTC, tillmo commented
For the example in the issue, I still get:
```
$ ./hets -g ~/temp/nesy5.dol 
Analyzing file file:///home/till/temp/nesy5.dol as library nesy5
Downloading NeSyPatterns.omn ...
Analyzing library http://www.ontohub.org/meta/NeSyPatterns
logic OWL
Analyzing spec http://www.ontohub.org/meta/NeSyPatterns
... loaded NeSyPatterns.omn
logic NeSyPatterns
Analyzing spec Model
file:///home/till/temp/nesy5.dol:4.3-5.1: *** Error:
Undefined class 'Model'
hets: user error (Stopped due to errors)
```

2022-09-23 16:27 UTC, mcodescu commented
With `www` in the empty prefix, I get
```
Analyzing file file:///home/mcodescu/repos/Hets2/nesyView.dol as library nesyView
Downloading ontohub:NeSyPatterns.omn ...
Analyzing library http://www.ontohub.org/meta/NeSyPatterns
logic OWL
Analyzing spec http://www.ontohub.org/meta/NeSyPatterns
... loaded ontohub:NeSyPatterns.omn
logic NeSyPatterns
Analyzing spec Model
file:///home/mcodescu/repos/Hets2/nesyView.dol:4.3-5.1: *** Error:
Undefined class 'gn_nesy0 : Model'
hets: user error (Stopped due to errors)

```

2022-09-23 16:31 UTC, tillmo requested changes
please remove the tracing stuff

2022-09-23 16:31 UTC, tillmo commented on NeSyPatterns/Sign.hs
> +import Debug.Trace (trace)
this should go

2022-09-23 16:31 UTC, tillmo commented on NeSyPatterns/Sign.hs
> +sigUnion s1 s2 = trace ("----sigUnion: s1: " ++ show s1 ++ ", s2: " ++ show s2) $ return $ unite s1 s2
this should go

2022-09-23 16:32 UTC, tillmo commented
> Have you added the `www` to the empty prefix?

oh, that has solved it, thanks.

2022-09-23 18:04 UTC, mcodescu commented
> With `www` in the empty prefix, I get
> 
> ```
> Analyzing file file:///home/mcodescu/repos/Hets2/nesyView.dol as library nesyView
> Downloading ontohub:NeSyPatterns.omn ...
> Analyzing library http://www.ontohub.org/meta/NeSyPatterns
> logic OWL
> Analyzing spec http://www.ontohub.org/meta/NeSyPatterns
> ... loaded ontohub:NeSyPatterns.omn
> logic NeSyPatterns
> Analyzing spec Model
> file:///home/mcodescu/repos/Hets2/nesyView.dol:4.3-5.1: *** Error:
> Undefined class 'gn_nesy0 : Model'
> hets: user error (Stopped due to errors)
> ```

I have added some tracing and this is the reason: we compare
```
scheme:file:
authority:IRIAuth {iriUserInfo = "", iriRegName = "nesyView.dol", iriPort = ""}
path:
query:?Model
fragment:
prefix:
iFragment:Model
isAbbrev:True
```
and
```
scheme:http:
authority:IRIAuth {iriUserInfo = "", iriRegName = "www.ontohub.org", iriPort = ""}
path:/meta/Model
query:
fragment:
prefix:
iFragment:Model
isAbbrev:True
```
and for one hasFullIRI holds while for the other it does not. Do you also get the same behavior?

2022-09-23 18:25 UTC, b-gehrke commented on NeSyPatterns/Sign.hs
> +import Debug.Trace (trace)
Removed

2022-09-23 18:25 UTC, b-gehrke commented on NeSyPatterns/Sign.hs
> +sigUnion s1 s2 = trace ("----sigUnion: s1: " ++ show s1 ++ ", s2: " ++ show s2) $ return $ unite s1 s2
Removed

2022-09-23 18:33 UTC, b-gehrke commented
> With `www` in the empty prefix, I get [...]

I don't get these errors. Can you post the contents of `nesyView.dol`?



> I have added some tracing and this is the reason: we compare
> and for one hasFullIRI holds while for the other it does not. Do you also get the same behavior?

Actually, for both `hasFullIRI` holds: The `iriScheme` is not empty in both cases (`file` and `http`). But, indeed, the IRIs are not identical. The absolute IRIs differ (`file://nesyView.dol?Model` and `http://www.ontohub.org/meta/Model`). This should not be as an empty prefix is defined and should overwrite the default default empty prefix.

2022-09-23 18:43 UTC, mcodescu commented
Sure, here it is:
```
%prefix( ontohub: <https://www.ontohub.org/meta/> )% 
logic NeSyPatterns    
pattern Model = data ontohub:NeSyPatterns.omn
  Model;
end
```

2022-09-23 18:53 UTC, mcodescu commented
> Actually, for both `hasFullIRI` holds

Of course, you're right.

2022-09-24 04:24 UTC, mcodescu commented
I get the same error with `:` instead of `ontohub:` and on a fresh copy of the repository on a machine that didn't have Hets installed before.

2022-09-24 06:21 UTC, b-gehrke commented
> ```
> %prefix( ontohub: <https://www.ontohub.org/meta/> )% 
>```

The problem is the `https` scheme. In the `NeSyPatterns.omn` the empty prefix is defined with `http` instead of `https`.

The following should go through:

```
%prefix( : <http://www.ontohub.org/meta/> )% 
logic NeSyPatterns    
pattern Model = data :NeSyPatterns.omn
  Model;
end
```


```
%prefix( ontohub: <http://www.ontohub.org/meta/> )% 
logic NeSyPatterns    
pattern Model = data ontohub:NeSyPatterns.omn
  ontohub:Model;
end
```

```
%prefix( : <http://www.ontohub.org/meta/>
  ontohub: <http://www.ontohub.org/meta/> )% 
logic NeSyPatterns    
pattern Model = data ontohub:NeSyPatterns.omn
  Model;
end
```

Maybe we should output a warning if prefixes defined in a data logic conflict with existing prefixes?

2022-09-24 07:20 UTC, tillmo commented
I have changed the ontology now:
```
Prefix: : <https://ontohub.org/meta/>`
```
This avoids these problems. `https` has become standard now.

I think it is also a good idea to issue a warning if prefixes conflict.

2022-09-24 07:21 UTC, tillmo approved these changes

2022-09-24 09:32 UTC, merged