2131 for the python api have a uniform datatype for sentences
spechub/Hets pull request #2136
Opened 2023-02-01 21:17 UTC by b-gehrke

Closes #2131

Adds rules for deriving `GHC.Generic`, `Data.Aeson`s `FromJSON`, `ToJSON`, `FromJSONKey`, and `ToJSONKey` instances for all datatypes that are also convertible to ATerms.

With these changes, JSON can be used as interchange format between the python api and the haskell api.

2023-02-07 19:23 UTC, tillmo requested changes
somehow, I would expect that the change from
```
deriving (Show, Eq, Ord, Typeable, Data)
```
to 
```
deriving (Show, Eq, Ord, Typeable, Data, Generic)
```
should also be made for the abstract syntaxes of all logics. Why is this not needed here?

2023-02-09 07:21 UTC, b-gehrke commented
This deriving is added with the new DrIFT-rule `Json`. For each ADT `A` it adds a derivation for `Generic` and default instances for `ToJSON` and `FromJSON`:

```hs
deriving instance GHC.Generics.Generic A
instance Data.Aeson.ToJSON A where
instance Data.Aeson.FromJSON A where
```

2023-02-14 20:06 UTC, b-gehrke commented
@tillmo Now the `ToJSON` and `FromJSON` classes are required for everything that require the `PrintTypeConv` class in `Logic.Logic`. This includes sentences. The derivings for Abstract Syntax elements are added with a new DrIFT Rule.

2023-02-16 09:04 UTC, tillmo approved these changes

2023-02-16 09:13 UTC, merged